variable "rg4" {}
variable "vnet" {}
variable "subnet" {}
variable "username" {}
variable "password" {}
variable "location" {}
variable "vm1_name" {}
variable "vm2_name" {}
variable "az_lb" {}
variable "az_lb_backend" {}
variable "az_natpool" {}
variable "az_natrule" {}
variable "az_outbound" {}
variable "az_lb_probe" {}
variable "az_lb_rule" {}
variable "az_pip" {}
variable "az_nic" {}
variable "vinet2" {}
variable "az_pip2" {}
variable "vm1_nic" {}
variable "subnet2" {}
variable "az_lb2" {}
variable "vm2_nic" {}
variable "vnet_network" {}
variable "vm1_size" {}
variable "back_add_pool" {}