variable "rg4" {}
variable "vnet4" {}
variable "subnet4" {}
variable "username" {}
variable "password" {}
variable "location" {}
variable "vm4_name" {}
variable "vm4_size" {}
variable "vm4_pip" {}
variable "vm4_nic" {}